/**
 * Header file for the PCode1ch2con1 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace Producer12 { namespace PCode1ch2con1 { 

class PCode1ch2con1 : public CodeBlock
{

public:
  // Define constructor and destructor
  PCode1ch2con1(int &pCh2);
  virtual ~PCode1ch2con1();

  void execute();

private:

  // Class variables
  int &pCh2;

  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} } } 
