# build.mk file for assignment3.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin
# protected region document description end

TARGETS+=bin/assignment3

assignment3/assignment3:
	@echo
	@echo "Building $@"
	@make -C assignment3 --no-print-directory

bin/assignment3: assignment3/assignment3 | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/assignment3 gets properly rebuild
assignment3/assignment3: assignment3/src/main.cpp Step/lib/libStep.a Controller/lib/libController.a LinearSystem/lib/libLinearSystem.a
assignment3/assignment3: assignment3/src/MainModel.cpp assignment3/include/MainModel.h
assignment3/assignment3: assignment3/src/stepTERRA.cpp assignment3/include/stepTERRA.h Step/include/Step/Step.h
assignment3/assignment3: assignment3/src/controllerTERRA.cpp assignment3/include/controllerTERRA.h Controller/include/Controller/Controller.h
assignment3/assignment3: assignment3/src/linearSystemTERRA.cpp assignment3/include/linearSystemTERRA.h LinearSystem/include/LinearSystem/LinearSystem.h

# protected region additional dependencies on begin
# protected region additional dependencies end