/**
 * Header file for the stepTERRA model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Step/Step.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace stepTERRA { 

class stepTERRA : public Sequential
{

public:
  // Define constructor and destructor
  stepTERRA(ChannelIn<double> *stepOutput);
  virtual ~stepTERRA();

private:

  // Model objects
  Step::Step *mystep20SIM;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
