/**
 * Source file for the linearSystemTerra model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "linearSystemTerra.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace linearSystemTerra { 

linearSystemTerra::linearSystemTerra(ChannelOut<double> *linearSystemInputTerra, ChannelIn<double> *linearSystemOutput) :
    Sequential(NULL)
{
  SETNAME(this, "linearSystemTerra");

  // Initialize model objects
  mylinearSystem20Sim = new LinearSystem::LinearSystem(linearSystemInputTerra, linearSystemOutput);
  SETNAME(mylinearSystem20Sim, "linearSystem20Sim");


  // Register model objects
  this->append_child(mylinearSystem20Sim);

  // protected region constructor on begin

  // protected region constructor end
}

linearSystemTerra::~linearSystemTerra()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin

  // protected region destructor end

  // Destroy model objects
  delete mylinearSystem20Sim;
}



// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} } 
