/**
 * Source file for the Producer12 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Producer12.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Producer12 { 



Producer12::Producer12(ChannelIn<int> *POUT1to1, ChannelIn<int> *POUT1to2) :
    Recursion<CSPConstruct>()
{
  SETNAME(this, "Producer12");

  // Initialize model objects
  myPCode1ch1con1 = new PCode1ch1con1::PCode1ch1con1(someValue);
  SETNAME(myPCode1ch1con1, "PCode1ch1con1");
  myPCode1ch2con1 = new PCode1ch2con1::PCode1ch2con1(anotherValue);
  SETNAME(myPCode1ch2con1, "PCode1ch2con1");
  myPwriter1ch1con1 = new Writer<int>(&someValue, POUT1to1);
  SETNAME(myPwriter1ch1con1, "Pwriter1ch1con1");
  myPwriter1ch2con1 = new Writer<int>(&anotherValue, POUT1to2);
  SETNAME(myPwriter1ch2con1, "Pwriter1ch2con1");

  // Create SEQUENTIAL1con1 group
  mySEQUENTIAL1con1 = new Sequential(
    (CSPConstruct *) myPCode1ch1con1,
    (CSPConstruct *) myPwriter1ch1con1,
    NULL
  );
  SETNAME(mySEQUENTIAL1con1, "SEQUENTIAL1con1");

  // Create SEQUENTIAL2con1 group
  mySEQUENTIAL2con1 = new Sequential(
    (CSPConstruct *) myPCode1ch2con1,
    (CSPConstruct *) myPwriter1ch2con1,
    NULL
  );
  SETNAME(mySEQUENTIAL2con1, "SEQUENTIAL2con1");

  // Create SEQUENTIAL1 group
  mySEQUENTIAL1 = new Sequential(
    (CSPConstruct *) mySEQUENTIAL1con1,
    (CSPConstruct *) mySEQUENTIAL2con1,
    NULL
  );
  SETNAME(mySEQUENTIAL1, "SEQUENTIAL1");

  // Register SEQUENTIAL1 as top-level recursive object
  setToActivate(mySEQUENTIAL1);
  setEvaluateCondition(true);


  // protected region constructor on begin

  // protected region constructor end
}

Producer12::~Producer12()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin

  // protected region destructor end

  // Destroy model groups
  delete mySEQUENTIAL1;
  delete mySEQUENTIAL1con1;
  delete mySEQUENTIAL2con1;

  // Destroy model objects
  delete myPwriter1ch2con1;
  delete myPwriter1ch1con1;
  delete myPCode1ch2con1;
  delete myPCode1ch1con1;
}



// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} } 
