# build.mk file for q3.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin

# protected region document description end

TARGETS+=bin/q3

q3/q3:
	@echo
	@echo "Building $@"
	@make -C q3 --no-print-directory

bin/q3: q3/q3 | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/q3 gets properly rebuild
q3/q3: q3/src/main.cpp Step/lib/libStep.a Controller/lib/libController.a LinearSystem/lib/libLinearSystem.a
q3/q3: q3/src/MainModel.cpp q3/include/MainModel.h
q3/q3: q3/src/stepTerra.cpp q3/include/stepTerra.h Step/include/Step/Step.h
q3/q3: q3/src/controllerTerra.cpp q3/include/controllerTerra.h Controller/include/Controller/Controller.h
q3/q3: q3/src/linearSystemTerra.cpp q3/include/linearSystemTerra.h LinearSystem/include/LinearSystem/LinearSystem.h

# protected region additional dependencies on begin

# protected region additional dependencies end