/**
 * Header file for the controllerTerra model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Controller/Controller.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace controllerTerra { 

class controllerTerra : public Sequential
{

public:
  // Define constructor and destructor
  controllerTerra(ChannelIn<double> *controllerOutput, ChannelOut<double> *linearSystemToControllerInput, ChannelOut<double> *stepInput);
  virtual ~controllerTerra();

private:

  // Model objects
  Controller::Controller *mycontroller20Sim;



  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
