/**
 * Header file for the MainModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "controllerTerra.h"
#include "linearSystemTerra.h"
#include "stepTerra.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { 

class MainModel : public Parallel
{

public:
  // Define constructor and destructor
  MainModel();
  virtual ~MainModel();

private:

  // Channel definitions
  UnbufferedChannel<double, One2In, Out2One> *mycontrollerTerracontrollerOutput_to_linearSystemTerralinearSystemInputTerraChannel;
  UnbufferedChannel<double, One2In, Out2One> *mylinearSystemTerralinearSystemOutput_to_controllerTerralinearSystemToControllerInputChannel;
  UnbufferedChannel<double, One2In, Out2One> *mystepTerrastepOutput_to_controllerTerrastepInputChannel;

  // Model objects
  controllerTerra::controllerTerra *mycontrollerTerra;
  linearSystemTerra::linearSystemTerra *mylinearSystemTerra;
  stepTerra::stepTerra *mystepTerra;



  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} 
