# build.mk file for newModel_deadlock.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.1
#
# protected region document description on begin

# protected region document description end

TARGETS+=bin/newModel_deadlock

newModel_deadlock/newModel_deadlock:
	@echo
	@echo "Building $@"
	@make -C newModel_deadlock --no-print-directory

bin/newModel_deadlock: newModel_deadlock/newModel_deadlock | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/newModel_deadlock gets properly rebuild
newModel_deadlock/newModel_deadlock: newModel_deadlock/src/main.cpp
newModel_deadlock/newModel_deadlock: newModel_deadlock/src/MainModel.cpp newModel_deadlock/include/MainModel.h
newModel_deadlock/newModel_deadlock: newModel_deadlock/src/Producer12.cpp newModel_deadlock/include/Producer12.h
newModel_deadlock/newModel_deadlock: newModel_deadlock/src/Producer12/PCode1ch1con1.cpp newModel_deadlock/include/Producer12/PCode1ch1con1.h
newModel_deadlock/newModel_deadlock: newModel_deadlock/src/Producer12/PCode1ch2con1.cpp newModel_deadlock/include/Producer12/PCode1ch2con1.h
newModel_deadlock/newModel_deadlock: newModel_deadlock/src/Consumer21.cpp newModel_deadlock/include/Consumer21.h
newModel_deadlock/newModel_deadlock: newModel_deadlock/src/Consumer21/CCode1.cpp newModel_deadlock/include/Consumer21/CCode1.h
newModel_deadlock/newModel_deadlock: newModel_deadlock/src/Consumer21/CCode2.cpp newModel_deadlock/include/Consumer21/CCode2.h

# protected region additional dependencies on begin

# protected region additional dependencies end