/**
 * Header file for the MainModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "controllerTERRA.h"
#include "linearSystemTERRA.h"
#include "stepTERRA.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { 

class MainModel : public Parallel
{

public:
  // Define constructor and destructor
  MainModel();
  virtual ~MainModel();

private:

  // Channel definitions
  UnbufferedChannel<double, One2In, Out2One> *mycontrollerTERRAcontrollerOutput_to_linearSystemTERRAlinearInputChannel;
  UnbufferedChannel<double, One2In, Out2One> *mylinearSystemTERRAlinearOutput_to_controllerTERRAlinearInputChannel;
  UnbufferedChannel<double, One2In, Out2One> *mystepTERRAstepOutput_to_controllerTERRAstepInputChannel;

  // Model objects
  controllerTERRA::controllerTERRA *mycontrollerTERRA;
  linearSystemTERRA::linearSystemTERRA *mylinearSystemTERRA;
  stepTERRA::stepTERRA *mystepTERRA;



  // protected region additional class members or functions on begin
  // protected region additional class members or functions end
};

// Close namespace(s)
} 
