/**
 * Source file for the CCode2 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Consumer21/CCode2.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Consumer21 { namespace CCode2 { 

CCode2::CCode2(int &CcodeVar) :
    CodeBlock(), CcodeVar(CcodeVar){
  SETNAME(this, "CCode2");

  // protected region constructor on begin

  // protected region constructor end
}

CCode2::~CCode2()
{
  // protected region destructor on begin

  // protected region destructor end
}

void CCode2::execute()
{
  // protected region execute code on begin
	printf("consumer2 got %d \n",CcodeVar);

  // protected region execute code end
}

// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} } } 
