/**
 * Source file for the MainModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "MainModel.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { 



MainModel::MainModel() :
    Recursion<CSProcess>()
{
  SETNAME(this, "MainModel");

  // Initialize channels
  myProducer12POUT1to1_to_Consumer21C2IN2Channel = new UnbufferedChannel<int, One2In, Out2One>();
  myProducer12POUT1to2_to_Consumer21C2IN1Channel = new UnbufferedChannel<int, One2In, Out2One>();

  // Initialize model objects
  myConsumer21 = new Consumer21::Consumer21(myProducer12POUT1to2_to_Consumer21C2IN1Channel, myProducer12POUT1to1_to_Consumer21C2IN2Channel);
  SETNAME(myConsumer21, "Consumer21");
  myProducer12 = new Producer12::Producer12(myProducer12POUT1to1_to_Consumer21C2IN2Channel, myProducer12POUT1to2_to_Consumer21C2IN1Channel);
  SETNAME(myProducer12, "Producer12");

  // Create PARALLEL group
  myPARALLEL = new Parallel(
    (CSPConstruct *) myConsumer21,
    (CSPConstruct *) myProducer12,
    NULL
  );
  SETNAME(myPARALLEL, "PARALLEL");

  // Register PARALLEL as top-level recursive object
  setToActivate(myPARALLEL);
  setEvaluateCondition(true);


  // protected region constructor on begin

  // protected region constructor end
}

MainModel::~MainModel()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin

  // protected region destructor end

  // Destroy model groups
  delete myPARALLEL;

  // Destroy model objects
  delete myProducer12;
  delete myConsumer21;

  // Destroy channels
  delete myProducer12POUT1to1_to_Consumer21C2IN2Channel;
  delete myProducer12POUT1to2_to_Consumer21C2IN1Channel;
}



// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} 
