/**
 * Source file for the MainModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "MainModel.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { 



MainModel::MainModel() :
    Recursion<CSProcess>()
{
  SETNAME(this, "MainModel");

  // Initialize channels
  myproducerPG0L10PORT_to_consumerCG0L10PORTChannel = new UnbufferedChannel<int, One2In, Out2One>();
  myproducerPG10L20port_to_consumerCG10L20PORTChannel = new UnbufferedChannel<int, One2In, Out2One>();
  myproducerPG20_to_consumerCG20PORTChannel = new UnbufferedChannel<int, One2In, Out2One>();

  // Initialize model objects
  myconsumer = new consumer::consumer(myproducerPG0L10PORT_to_consumerCG0L10PORTChannel, myproducerPG10L20port_to_consumerCG10L20PORTChannel, myproducerPG20_to_consumerCG20PORTChannel);
  SETNAME(myconsumer, "consumer");
  myproducer = new producer::producer(myproducerPG0L10PORT_to_consumerCG0L10PORTChannel, myproducerPG10L20port_to_consumerCG10L20PORTChannel, myproducerPG20_to_consumerCG20PORTChannel);
  SETNAME(myproducer, "producer");

  // Create PARALLEL group
  myPARALLEL = new Parallel(
    (CSPConstruct *) myproducer,
    (CSPConstruct *) myconsumer,
    NULL
  );
  SETNAME(myPARALLEL, "PARALLEL");

  // Register PARALLEL as top-level recursive object
  setToActivate(myPARALLEL);
  setEvaluateCondition(true);


  // protected region constructor on begin

  // protected region constructor end
}

MainModel::~MainModel()
{
  // TODO Properly destroy all additional objects that got defined in the constructor

  // protected region destructor on begin

  // protected region destructor end

  // Destroy model groups
  delete myPARALLEL;

  // Destroy model objects
  delete myproducer;
  delete myconsumer;

  // Destroy channels
  delete myproducerPG0L10PORT_to_consumerCG0L10PORTChannel;
  delete myproducerPG10L20port_to_consumerCG10L20PORTChannel;
  delete myproducerPG20_to_consumerCG20PORTChannel;
}



// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} 
