/**
 * Source file for the CCode1 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#include "Consumer21/CCode1.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

namespace MainModel { namespace Consumer21 { namespace CCode1 { 

CCode1::CCode1(int &CCodeaVar) :
    CodeBlock(), CCodeaVar(CCodeaVar){
  SETNAME(this, "CCode1");

  // protected region constructor on begin

  // protected region constructor end
}

CCode1::~CCode1()
{
  // protected region destructor on begin

  // protected region destructor end
}

void CCode1::execute()
{
  // protected region execute code on begin
	printf("value recieved on the consumer from channel 1 %d \n",CCodeaVar);
  // protected region execute code end
}

// protected region additional functions on begin

// protected region additional functions end

// Close namespace(s)
} } } 
