/**
 * Header file for the MainModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Consumer21.h"
#include "Producer12.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { 

class MainModel : public Recursion<CSProcess>
{

public:
  // Define constructor and destructor
  MainModel();
  virtual ~MainModel();



private:

  // Channel definitions
  UnbufferedChannel<int, One2In, Out2One> *myProducer12POUT1to1_to_Consumer21C2IN2Channel;
  UnbufferedChannel<int, One2In, Out2One> *myProducer12POUT1to2_to_Consumer21C2IN1Channel;

  // Model objects
  Consumer21::Consumer21 *myConsumer21;
  Producer12::Producer12 *myProducer12;

  // Model groups
  Parallel *myPARALLEL;

  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} 
