/**
 * Header file for the Producer12 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Producer12/PCode1ch1con1.h"
#include "Producer12/PCode1ch2con1.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace Producer12 { 

class Producer12 : public Recursion<CSPConstruct>
{

public:
  // Define constructor and destructor
  Producer12(ChannelIn<int> *POUT1to1, ChannelIn<int> *POUT1to2);
  virtual ~Producer12();



private:

  // Class variables
  int anotherValue;
  int someValue;

  // Model objects
  PCode1ch1con1::PCode1ch1con1 *myPCode1ch1con1;
  PCode1ch2con1::PCode1ch2con1 *myPCode1ch2con1;
  Writer<int> *myPwriter1ch1con1;
  Writer<int> *myPwriter1ch2con1;

  // Model groups
  Sequential *mySEQUENTIAL1;
  Sequential *mySEQUENTIAL1con1;
  Sequential *mySEQUENTIAL2con1;

  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
