/**
 * Header file for the takeInputs model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"
// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace producer { namespace takeInputs { 

class takeInputs : public CodeBlock
{

public:
  // Define constructor and destructor
  takeInputs(int &pCode);
  virtual ~takeInputs();

  void execute();

private:

  // Class variables
  int &pCode;

  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} } } 
