/**
 * Header file for the Consumer21 model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "Consumer21/CCode1.h"
#include "Consumer21/CCode2.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace Consumer21 { 

class Consumer21 : public Recursion<CSPConstruct>
{

public:
  // Define constructor and destructor
  Consumer21(ChannelOut<int> *C2IN1, ChannelOut<int> *C2IN2);
  virtual ~Consumer21();



private:

  // Class variables
  int a;
  int b;

  // Model objects
  Reader<int> *myC2R1;
  Reader<int> *myC2R2;
  CCode1::CCode1 *myCCode1;
  CCode2::CCode2 *myCCode2;

  // Model groups
  Sequential *mySEQUENTIAL;
  Sequential *mySEQUENTIAL_C21;
  Sequential *mySEQUENTIAL_C22;

  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
