/**
 * Header file for the linearSystemTERRA model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.3
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "LinearSystem/LinearSystem.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace linearSystemTERRA { 

class linearSystemTERRA : public Sequential
{

public:
  // Define constructor and destructor
  linearSystemTERRA(ChannelOut<double> *linearInput, ChannelIn<double> *linearOutput);
  virtual ~linearSystemTERRA();

private:

  // Model objects
  LinearSystem::LinearSystem *mylinearSystem20Sim;



  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
