# build.mk file for assignment3_display.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.3
#
# protected region document description on begin

# protected region document description end

TARGETS+=bin/assignment3_display

assignment3_display/assignment3_display:
	@echo
	@echo "Building $@"
	@make -C assignment3_display --no-print-directory

bin/assignment3_display: assignment3_display/assignment3_display | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/assignment3_display gets properly rebuild
assignment3_display/assignment3_display: assignment3_display/src/main.cpp Step/lib/libStep.a Controller/lib/libController.a LinearSystem/lib/libLinearSystem.a
assignment3_display/assignment3_display: assignment3_display/src/MainModel.cpp assignment3_display/include/MainModel.h
assignment3_display/assignment3_display: assignment3_display/src/stepTERRA.cpp assignment3_display/include/stepTERRA.h Step/include/Step/Step.h
assignment3_display/assignment3_display: assignment3_display/src/controllerTERRA.cpp assignment3_display/include/controllerTERRA.h Controller/include/Controller/Controller.h
assignment3_display/assignment3_display: assignment3_display/src/linearSystemTERRA.cpp assignment3_display/include/linearSystemTERRA.h LinearSystem/include/LinearSystem/LinearSystem.h

# protected region additional dependencies on begin

# protected region additional dependencies end