/**
 * Header file for the consumer model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "consumer/readerG0L10.h"
#include "consumer/readerG10L20.h"
#include "consumer/readerG20L30.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { namespace consumer { 

class consumer : public Alternative
{

public:
  // Define constructor and destructor
  consumer(GuardedChannelOut<int> *CG0L10PORT, GuardedChannelOut<int> *CG10L20PORT, GuardedChannelOut<int> *CG20PORT);
  virtual ~consumer();



private:

  // Class variables
  int g0l10;
  int g10l20;
  int g20;

  // Model objects
  GuardedReader<int> *myg0l10Reader;
  GuardedReader<int> *myg10l20Reader;
  GuardedReader<int> *myg20Reader;
  readerG0L10::readerG0L10 *myreaderG0L10;
  readerG10L20::readerG10L20 *myreaderG10L20;
  readerG20L30::readerG20L30 *myreaderG20L30;

  // Model groups
  Sequential *mySEQUENTIAL_G0;
  Sequential *mySEQUENTIAL_G10;
  Sequential *mySEQUENTIAL_G20;

  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} } 
