/**
 * Header file for the MainModel model
 * Generated by the TERRA CSPm2LUNA generator version 1.1.1
 *
 * protected region document description on begin
 *
 * protected region document description end
 */

#pragma once

#include "csp/CSP.h"

// Models
#include "consumer.h"
#include "producer.h"

// protected region additional headers on begin
// Each additional header should get a corresponding dependency in the Makefile
// protected region additional headers end

using namespace LUNA::CSP;

namespace MainModel { 

class MainModel : public Recursion<CSProcess>
{

public:
  // Define constructor and destructor
  MainModel();
  virtual ~MainModel();



private:

  // Channel definitions
  UnbufferedChannel<int, One2In, Out2One> *myproducerPG0L10PORT_to_consumerCG0L10PORTChannel;
  UnbufferedChannel<int, One2In, Out2One> *myproducerPG10L20port_to_consumerCG10L20PORTChannel;
  UnbufferedChannel<int, One2In, Out2One> *myproducerPG20_to_consumerCG20PORTChannel;

  // Model objects
  consumer::consumer *myconsumer;
  producer::producer *myproducer;

  // Model groups
  Parallel *myPARALLEL;

  // protected region additional class members or functions on begin

  // protected region additional class members or functions end
};

// Close namespace(s)
} 
