# build.mk file for alternate.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.1
#
# protected region document description on begin

# protected region document description end

TARGETS+=bin/alternate

alternate/alternate:
	@echo
	@echo "Building $@"
	@make -C alternate --no-print-directory

bin/alternate: alternate/alternate | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/alternate gets properly rebuild
alternate/alternate: alternate/src/main.cpp
alternate/alternate: alternate/src/MainModel.cpp alternate/include/MainModel.h
alternate/alternate: alternate/src/producer.cpp alternate/include/producer.h
alternate/alternate: alternate/src/producer/takeInputs.cpp alternate/include/producer/takeInputs.h
alternate/alternate: alternate/src/consumer.cpp alternate/include/consumer.h
alternate/alternate: alternate/src/consumer/readerG0L10.cpp alternate/include/consumer/readerG0L10.h
alternate/alternate: alternate/src/consumer/readerG10L20.cpp alternate/include/consumer/readerG10L20.h
alternate/alternate: alternate/src/consumer/readerG20L30.cpp alternate/include/consumer/readerG20L30.h

# protected region additional dependencies on begin

# protected region additional dependencies end