# build.mk file for deadlockfree.cspm, provide information to 'project MakeFile' 
# Generated by the TERRA CSPm2LUNA generator version 1.1.1
#
# protected region document description on begin

# protected region document description end

TARGETS+=bin/deadlockfree

deadlockfree/deadlockfree:
	@echo
	@echo "Building $@"
	@make -C deadlockfree --no-print-directory

bin/deadlockfree: deadlockfree/deadlockfree | bin
	@cp $^ $@
	@echo "Build $@"

# Additional dependencies to ensure that bin/deadlockfree gets properly rebuild
deadlockfree/deadlockfree: deadlockfree/src/main.cpp
deadlockfree/deadlockfree: deadlockfree/src/MainModel.cpp deadlockfree/include/MainModel.h
deadlockfree/deadlockfree: deadlockfree/src/Consumer21.cpp deadlockfree/include/Consumer21.h
deadlockfree/deadlockfree: deadlockfree/src/Consumer21/CCode1.cpp deadlockfree/include/Consumer21/CCode1.h
deadlockfree/deadlockfree: deadlockfree/src/Consumer21/CCode2.cpp deadlockfree/include/Consumer21/CCode2.h
deadlockfree/deadlockfree: deadlockfree/src/Producer12.cpp deadlockfree/include/Producer12.h
deadlockfree/deadlockfree: deadlockfree/src/Producer12/PCode1ch1con1.cpp deadlockfree/include/Producer12/PCode1ch1con1.h
deadlockfree/deadlockfree: deadlockfree/src/Producer12/PCode1ch2con1.cpp deadlockfree/include/Producer12/PCode1ch2con1.h

# protected region additional dependencies on begin

# protected region additional dependencies end